server:
  address: ":8777"
  grpc_address: ":50055"
  shutdown_timeout: 30s

database:
  type: "mongodb"
  mongodb:
    uri: "mongodb://mongo:27017"
    database: "logistics"

kafka:
  brokers:
    - "kafka:29092"
  ptopics:
    - "payment-events"
    - "telegram-notifications"
    - "register-delivery"
  ctopics: 
    - "expired-packages"
    - "paid-packages"
  groupID: "auction-consumers"
  version: "7.3.0"