// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: calculator/calculator.proto

package calculatorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CalculatorService_CalculateDeliveryCost_FullMethodName = "/calculator.CalculatorService/CalculateDeliveryCost"
	CalculatorService_CalculateByTariffCode_FullMethodName = "/calculator.CalculatorService/CalculateByTariffCode"
	CalculatorService_GetTariffList_FullMethodName         = "/calculator.CalculatorService/GetTariffList"
)

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	CalculateDeliveryCost(ctx context.Context, in *CalculateDeliveryCostRequest, opts ...grpc.CallOption) (*CalculateDeliveryCostResponse, error)
	CalculateByTariffCode(ctx context.Context, in *CalculateByTariffRequest, opts ...grpc.CallOption) (*CalculateDeliveryCostResponse, error)
	GetTariffList(ctx context.Context, in *TariffListRequest, opts ...grpc.CallOption) (*TariffListResponse, error)
}

type calculatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorServiceClient(cc grpc.ClientConnInterface) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) CalculateDeliveryCost(ctx context.Context, in *CalculateDeliveryCostRequest, opts ...grpc.CallOption) (*CalculateDeliveryCostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateDeliveryCostResponse)
	err := c.cc.Invoke(ctx, CalculatorService_CalculateDeliveryCost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) CalculateByTariffCode(ctx context.Context, in *CalculateByTariffRequest, opts ...grpc.CallOption) (*CalculateDeliveryCostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateDeliveryCostResponse)
	err := c.cc.Invoke(ctx, CalculatorService_CalculateByTariffCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) GetTariffList(ctx context.Context, in *TariffListRequest, opts ...grpc.CallOption) (*TariffListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TariffListResponse)
	err := c.cc.Invoke(ctx, CalculatorService_GetTariffList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
// All implementations must embed UnimplementedCalculatorServiceServer
// for forward compatibility.
type CalculatorServiceServer interface {
	CalculateDeliveryCost(context.Context, *CalculateDeliveryCostRequest) (*CalculateDeliveryCostResponse, error)
	CalculateByTariffCode(context.Context, *CalculateByTariffRequest) (*CalculateDeliveryCostResponse, error)
	GetTariffList(context.Context, *TariffListRequest) (*TariffListResponse, error)
	mustEmbedUnimplementedCalculatorServiceServer()
}

// UnimplementedCalculatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCalculatorServiceServer struct{}

func (UnimplementedCalculatorServiceServer) CalculateDeliveryCost(context.Context, *CalculateDeliveryCostRequest) (*CalculateDeliveryCostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateDeliveryCost not implemented")
}
func (UnimplementedCalculatorServiceServer) CalculateByTariffCode(context.Context, *CalculateByTariffRequest) (*CalculateDeliveryCostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateByTariffCode not implemented")
}
func (UnimplementedCalculatorServiceServer) GetTariffList(context.Context, *TariffListRequest) (*TariffListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTariffList not implemented")
}
func (UnimplementedCalculatorServiceServer) mustEmbedUnimplementedCalculatorServiceServer() {}
func (UnimplementedCalculatorServiceServer) testEmbeddedByValue()                           {}

// UnsafeCalculatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculatorServiceServer will
// result in compilation errors.
type UnsafeCalculatorServiceServer interface {
	mustEmbedUnimplementedCalculatorServiceServer()
}

func RegisterCalculatorServiceServer(s grpc.ServiceRegistrar, srv CalculatorServiceServer) {
	// If the following call pancis, it indicates UnimplementedCalculatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CalculatorService_ServiceDesc, srv)
}

func _CalculatorService_CalculateDeliveryCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateDeliveryCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).CalculateDeliveryCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalculatorService_CalculateDeliveryCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).CalculateDeliveryCost(ctx, req.(*CalculateDeliveryCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_CalculateByTariffCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateByTariffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).CalculateByTariffCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalculatorService_CalculateByTariffCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).CalculateByTariffCode(ctx, req.(*CalculateByTariffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_GetTariffList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TariffListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).GetTariffList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalculatorService_GetTariffList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).GetTariffList(ctx, req.(*TariffListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CalculatorService_ServiceDesc is the grpc.ServiceDesc for CalculatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalculatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateDeliveryCost",
			Handler:    _CalculatorService_CalculateDeliveryCost_Handler,
		},
		{
			MethodName: "CalculateByTariffCode",
			Handler:    _CalculatorService_CalculateByTariffCode_Handler,
		},
		{
			MethodName: "GetTariffList",
			Handler:    _CalculatorService_GetTariffList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calculator/calculator.proto",
}
