// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: calculator/calculator.proto

package calculatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateDeliveryCostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weight        float64                `protobuf:"fixed64,1,opt,name=weight,proto3" json:"weight,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Length        int32                  `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	Width         int32                  `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateDeliveryCostRequest) Reset() {
	*x = CalculateDeliveryCostRequest{}
	mi := &file_calculator_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDeliveryCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDeliveryCostRequest) ProtoMessage() {}

func (x *CalculateDeliveryCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDeliveryCostRequest.ProtoReflect.Descriptor instead.
func (*CalculateDeliveryCostRequest) Descriptor() ([]byte, []int) {
	return file_calculator_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateDeliveryCostRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CalculateDeliveryCostRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CalculateDeliveryCostRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *CalculateDeliveryCostRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CalculateDeliveryCostRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *CalculateDeliveryCostRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CalculateDeliveryCostRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type CalculateDeliveryCostResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Cost           float64                `protobuf:"fixed64,1,opt,name=cost,proto3" json:"cost,omitempty"`
	EstimatedHours int32                  `protobuf:"varint,2,opt,name=estimated_hours,json=estimatedHours,proto3" json:"estimated_hours,omitempty"`
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CalculateDeliveryCostResponse) Reset() {
	*x = CalculateDeliveryCostResponse{}
	mi := &file_calculator_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateDeliveryCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateDeliveryCostResponse) ProtoMessage() {}

func (x *CalculateDeliveryCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateDeliveryCostResponse.ProtoReflect.Descriptor instead.
func (*CalculateDeliveryCostResponse) Descriptor() ([]byte, []int) {
	return file_calculator_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateDeliveryCostResponse) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *CalculateDeliveryCostResponse) GetEstimatedHours() int32 {
	if x != nil {
		return x.EstimatedHours
	}
	return 0
}

func (x *CalculateDeliveryCostResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_calculator_calculator_proto protoreflect.FileDescriptor

const file_calculator_calculator_proto_rawDesc = "" +
	"\n" +
	"\x1bcalculator/calculator.proto\x12\n" +
	"calculator\"\xba\x01\n" +
	"\x1cCalculateDeliveryCostRequest\x12\x16\n" +
	"\x06weight\x18\x01 \x01(\x01R\x06weight\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x16\n" +
	"\x06length\x18\x05 \x01(\x05R\x06length\x12\x14\n" +
	"\x05width\x18\x06 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\x05R\x06height\"x\n" +
	"\x1dCalculateDeliveryCostResponse\x12\x12\n" +
	"\x04cost\x18\x01 \x01(\x01R\x04cost\x12'\n" +
	"\x0festimated_hours\x18\x02 \x01(\x05R\x0eestimatedHours\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency2\x81\x01\n" +
	"\x11CalculatorService\x12l\n" +
	"\x15CalculateDeliveryCost\x12(.calculator.CalculateDeliveryCostRequest\x1a).calculator.CalculateDeliveryCostResponseBCZAgithub.com/maksroxx/DeliveryService/proto/calculator;calculatorpbb\x06proto3"

var (
	file_calculator_calculator_proto_rawDescOnce sync.Once
	file_calculator_calculator_proto_rawDescData []byte
)

func file_calculator_calculator_proto_rawDescGZIP() []byte {
	file_calculator_calculator_proto_rawDescOnce.Do(func() {
		file_calculator_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculator_calculator_proto_rawDesc), len(file_calculator_calculator_proto_rawDesc)))
	})
	return file_calculator_calculator_proto_rawDescData
}

var file_calculator_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_calculator_calculator_proto_goTypes = []any{
	(*CalculateDeliveryCostRequest)(nil),  // 0: calculator.CalculateDeliveryCostRequest
	(*CalculateDeliveryCostResponse)(nil), // 1: calculator.CalculateDeliveryCostResponse
}
var file_calculator_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.CalculatorService.CalculateDeliveryCost:input_type -> calculator.CalculateDeliveryCostRequest
	1, // 1: calculator.CalculatorService.CalculateDeliveryCost:output_type -> calculator.CalculateDeliveryCostResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_calculator_proto_init() }
func file_calculator_calculator_proto_init() {
	if File_calculator_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_calculator_proto_rawDesc), len(file_calculator_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_calculator_proto_depIdxs,
		MessageInfos:      file_calculator_calculator_proto_msgTypes,
	}.Build()
	File_calculator_calculator_proto = out.File
	file_calculator_calculator_proto_goTypes = nil
	file_calculator_calculator_proto_depIdxs = nil
}
