server:
  address: ":8555"
  shutdown_timeout: 30s

database:
  type: "mongodb"
  mongodb:
    uri: "mongodb://mongo:27017"
    database: "logistics"

kafka:
  brokers:
    - "kafka:29092"
  topics: 
    - "telegram-notifications"
  groupID: "telegram-consumers"
  version: "7.3.0"

telegram:
  token: "1132891459:AAEkupVlKVEedmKIY7UmaU2ujyv9mOn6p1M"

clients:
  auth: "auth:50052"
  package: "package:50054"