// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: database/database.proto

package databasepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Package struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PackageId      string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Weight         float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Length         int32                  `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Width          int32                  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height         int32                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	From           string                 `protobuf:"bytes,7,opt,name=from,proto3" json:"from,omitempty"`
	To             string                 `protobuf:"bytes,8,opt,name=to,proto3" json:"to,omitempty"`
	Address        string                 `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	PaymentStatus  string                 `protobuf:"bytes,10,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	Status         string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	Cost           float64                `protobuf:"fixed64,12,opt,name=cost,proto3" json:"cost,omitempty"`
	EstimatedHours int32                  `protobuf:"varint,13,opt,name=estimated_hours,json=estimatedHours,proto3" json:"estimated_hours,omitempty"`
	RemainingHours int32                  `protobuf:"varint,14,opt,name=remaining_hours,json=remainingHours,proto3" json:"remaining_hours,omitempty"`
	Currency       string                 `protobuf:"bytes,15,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_database_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_database_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_database_database_proto_rawDescGZIP(), []int{0}
}

func (x *Package) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *Package) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Package) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Package) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Package) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Package) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Package) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Package) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Package) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Package) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *Package) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Package) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Package) GetEstimatedHours() int32 {
	if x != nil {
		return x.EstimatedHours
	}
	return 0
}

func (x *Package) GetRemainingHours() int32 {
	if x != nil {
		return x.RemainingHours
	}
	return 0
}

func (x *Package) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Package) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PackageFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAfter  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_after,json=createdAfter,proto3" json:"created_after,omitempty"`
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageFilter) Reset() {
	*x = PackageFilter{}
	mi := &file_database_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageFilter) ProtoMessage() {}

func (x *PackageFilter) ProtoReflect() protoreflect.Message {
	mi := &file_database_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageFilter.ProtoReflect.Descriptor instead.
func (*PackageFilter) Descriptor() ([]byte, []int) {
	return file_database_database_proto_rawDescGZIP(), []int{1}
}

func (x *PackageFilter) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PackageFilter) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PackageFilter) GetCreatedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAfter
	}
	return nil
}

func (x *PackageFilter) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PackageFilter) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PackageUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PaymentStatus string                 `protobuf:"bytes,2,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageUpdate) Reset() {
	*x = PackageUpdate{}
	mi := &file_database_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageUpdate) ProtoMessage() {}

func (x *PackageUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_database_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageUpdate.ProtoReflect.Descriptor instead.
func (*PackageUpdate) Descriptor() ([]byte, []int) {
	return file_database_database_proto_rawDescGZIP(), []int{2}
}

func (x *PackageUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PackageUpdate) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

type PackageID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageID) Reset() {
	*x = PackageID{}
	mi := &file_database_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageID) ProtoMessage() {}

func (x *PackageID) ProtoReflect() protoreflect.Message {
	mi := &file_database_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageID.ProtoReflect.Descriptor instead.
func (*PackageID) Descriptor() ([]byte, []int) {
	return file_database_database_proto_rawDescGZIP(), []int{3}
}

func (x *PackageID) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

type PackageStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageStatus) Reset() {
	*x = PackageStatus{}
	mi := &file_database_database_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageStatus) ProtoMessage() {}

func (x *PackageStatus) ProtoReflect() protoreflect.Message {
	mi := &file_database_database_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageStatus.ProtoReflect.Descriptor instead.
func (*PackageStatus) Descriptor() ([]byte, []int) {
	return file_database_database_proto_rawDescGZIP(), []int{4}
}

func (x *PackageStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_database_database_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_database_database_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_database_database_proto_rawDescGZIP(), []int{5}
}

type PackageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []*Package             `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageList) Reset() {
	*x = PackageList{}
	mi := &file_database_database_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageList) ProtoMessage() {}

func (x *PackageList) ProtoReflect() protoreflect.Message {
	mi := &file_database_database_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageList.ProtoReflect.Descriptor instead.
func (*PackageList) Descriptor() ([]byte, []int) {
	return file_database_database_proto_rawDescGZIP(), []int{6}
}

func (x *PackageList) GetPackages() []*Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

var File_database_database_proto protoreflect.FileDescriptor

const file_database_database_proto_rawDesc = "" +
	"\n" +
	"\x17database/database.proto\x12\bdelivery\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x03\n" +
	"\aPackage\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x01R\x06weight\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x05R\x06length\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\x12\x12\n" +
	"\x04from\x18\a \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\b \x01(\tR\x02to\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\x12%\n" +
	"\x0epayment_status\x18\n" +
	" \x01(\tR\rpaymentStatus\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x12\n" +
	"\x04cost\x18\f \x01(\x01R\x04cost\x12'\n" +
	"\x0festimated_hours\x18\r \x01(\x05R\x0eestimatedHours\x12'\n" +
	"\x0fremaining_hours\x18\x0e \x01(\x05R\x0eremainingHours\x12\x1a\n" +
	"\bcurrency\x18\x0f \x01(\tR\bcurrency\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xaf\x01\n" +
	"\rPackageFilter\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12?\n" +
	"\rcreated_after\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fcreatedAfter\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\"N\n" +
	"\rPackageUpdate\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0epayment_status\x18\x02 \x01(\tR\rpaymentStatus\"*\n" +
	"\tPackageID\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\"'\n" +
	"\rPackageStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\a\n" +
	"\x05Empty\"<\n" +
	"\vPackageList\x12-\n" +
	"\bpackages\x18\x01 \x03(\v2\x11.delivery.PackageR\bpackages2\xeb\x03\n" +
	"\x0ePackageService\x124\n" +
	"\n" +
	"GetPackage\x12\x13.delivery.PackageID\x1a\x11.delivery.Package\x12@\n" +
	"\x0eGetAllPackages\x12\x17.delivery.PackageFilter\x1a\x15.delivery.PackageList\x12A\n" +
	"\x0fGetUserPackages\x12\x17.delivery.PackageFilter\x1a\x15.delivery.PackageList\x125\n" +
	"\rCreatePackage\x12\x11.delivery.Package\x1a\x11.delivery.Package\x125\n" +
	"\rUpdatePackage\x12\x11.delivery.Package\x1a\x11.delivery.Package\x125\n" +
	"\rDeletePackage\x12\x13.delivery.PackageID\x1a\x0f.delivery.Empty\x127\n" +
	"\rCancelPackage\x12\x13.delivery.PackageID\x1a\x11.delivery.Package\x12@\n" +
	"\x10GetPackageStatus\x12\x13.delivery.PackageID\x1a\x17.delivery.PackageStatusBHZFgithub.com/maksroxx/DeliveryService/proto/database/database;databasepbb\x06proto3"

var (
	file_database_database_proto_rawDescOnce sync.Once
	file_database_database_proto_rawDescData []byte
)

func file_database_database_proto_rawDescGZIP() []byte {
	file_database_database_proto_rawDescOnce.Do(func() {
		file_database_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_database_database_proto_rawDesc), len(file_database_database_proto_rawDesc)))
	})
	return file_database_database_proto_rawDescData
}

var file_database_database_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_database_database_proto_goTypes = []any{
	(*Package)(nil),               // 0: delivery.Package
	(*PackageFilter)(nil),         // 1: delivery.PackageFilter
	(*PackageUpdate)(nil),         // 2: delivery.PackageUpdate
	(*PackageID)(nil),             // 3: delivery.PackageID
	(*PackageStatus)(nil),         // 4: delivery.PackageStatus
	(*Empty)(nil),                 // 5: delivery.Empty
	(*PackageList)(nil),           // 6: delivery.PackageList
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_database_database_proto_depIdxs = []int32{
	7,  // 0: delivery.Package.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: delivery.PackageFilter.created_after:type_name -> google.protobuf.Timestamp
	0,  // 2: delivery.PackageList.packages:type_name -> delivery.Package
	3,  // 3: delivery.PackageService.GetPackage:input_type -> delivery.PackageID
	1,  // 4: delivery.PackageService.GetAllPackages:input_type -> delivery.PackageFilter
	1,  // 5: delivery.PackageService.GetUserPackages:input_type -> delivery.PackageFilter
	0,  // 6: delivery.PackageService.CreatePackage:input_type -> delivery.Package
	0,  // 7: delivery.PackageService.UpdatePackage:input_type -> delivery.Package
	3,  // 8: delivery.PackageService.DeletePackage:input_type -> delivery.PackageID
	3,  // 9: delivery.PackageService.CancelPackage:input_type -> delivery.PackageID
	3,  // 10: delivery.PackageService.GetPackageStatus:input_type -> delivery.PackageID
	0,  // 11: delivery.PackageService.GetPackage:output_type -> delivery.Package
	6,  // 12: delivery.PackageService.GetAllPackages:output_type -> delivery.PackageList
	6,  // 13: delivery.PackageService.GetUserPackages:output_type -> delivery.PackageList
	0,  // 14: delivery.PackageService.CreatePackage:output_type -> delivery.Package
	0,  // 15: delivery.PackageService.UpdatePackage:output_type -> delivery.Package
	5,  // 16: delivery.PackageService.DeletePackage:output_type -> delivery.Empty
	0,  // 17: delivery.PackageService.CancelPackage:output_type -> delivery.Package
	4,  // 18: delivery.PackageService.GetPackageStatus:output_type -> delivery.PackageStatus
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_database_database_proto_init() }
func file_database_database_proto_init() {
	if File_database_database_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_database_database_proto_rawDesc), len(file_database_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_database_database_proto_goTypes,
		DependencyIndexes: file_database_database_proto_depIdxs,
		MessageInfos:      file_database_database_proto_msgTypes,
	}.Build()
	File_database_database_proto = out.File
	file_database_database_proto_goTypes = nil
	file_database_database_proto_depIdxs = nil
}
