// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: auction/auction.proto

package auctionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_auction_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_auction_auction_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *BidRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BidRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_auction_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_auction_auction_proto_rawDescGZIP(), []int{1}
}

func (x *BidResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BidResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BidsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidsRequest) Reset() {
	*x = BidsRequest{}
	mi := &file_auction_auction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidsRequest) ProtoMessage() {}

func (x *BidsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_auction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidsRequest.ProtoReflect.Descriptor instead.
func (*BidsRequest) Descriptor() ([]byte, []int) {
	return file_auction_auction_proto_rawDescGZIP(), []int{2}
}

func (x *BidsRequest) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

type BidsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bids          []*Bid                 `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidsResponse) Reset() {
	*x = BidsResponse{}
	mi := &file_auction_auction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidsResponse) ProtoMessage() {}

func (x *BidsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_auction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidsResponse.ProtoReflect.Descriptor instead.
func (*BidsResponse) Descriptor() ([]byte, []int) {
	return file_auction_auction_proto_rawDescGZIP(), []int{3}
}

func (x *BidsResponse) GetBids() []*Bid {
	if x != nil {
		return x.Bids
	}
	return nil
}

type Bid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidId         string                 `protobuf:"bytes,1,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"`
	PackageId     string                 `protobuf:"bytes,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bid) Reset() {
	*x = Bid{}
	mi := &file_auction_auction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_auction_auction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_auction_auction_proto_rawDescGZIP(), []int{4}
}

func (x *Bid) GetBidId() string {
	if x != nil {
		return x.BidId
	}
	return ""
}

func (x *Bid) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *Bid) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Bid) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Bid) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Packages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       []*Package             `protobuf:"bytes,1,rep,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packages) Reset() {
	*x = Packages{}
	mi := &file_auction_auction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packages) ProtoMessage() {}

func (x *Packages) ProtoReflect() protoreflect.Message {
	mi := &file_auction_auction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packages.ProtoReflect.Descriptor instead.
func (*Packages) Descriptor() ([]byte, []int) {
	return file_auction_auction_proto_rawDescGZIP(), []int{5}
}

func (x *Packages) GetPackage() []*Package {
	if x != nil {
		return x.Package
	}
	return nil
}

type Package struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Cost          float64                `protobuf:"fixed64,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	TariffCode    string                 `protobuf:"bytes,7,opt,name=tariff_code,json=tariffCode,proto3" json:"tariff_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_auction_auction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_auction_auction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_auction_auction_proto_rawDescGZIP(), []int{6}
}

func (x *Package) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *Package) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Package) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Package) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Package) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Package) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Package) GetTariffCode() string {
	if x != nil {
		return x.TariffCode
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_auction_auction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_auction_auction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_auction_auction_proto_rawDescGZIP(), []int{7}
}

var File_auction_auction_proto protoreflect.FileDescriptor

const file_auction_auction_proto_rawDesc = "" +
	"\n" +
	"\x15auction/auction.proto\x12\aauction\"\\\n" +
	"\n" +
	"BidRequest\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"?\n" +
	"\vBidResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\vBidsRequest\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\"0\n" +
	"\fBidsResponse\x12 \n" +
	"\x04bids\x18\x01 \x03(\v2\f.auction.BidR\x04bids\"\x8a\x01\n" +
	"\x03Bid\x12\x15\n" +
	"\x06bid_id\x18\x01 \x01(\tR\x05bidId\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\tR\tpackageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"6\n" +
	"\bPackages\x12*\n" +
	"\apackage\x18\x01 \x03(\v2\x10.auction.PackageR\apackage\"\xb5\x01\n" +
	"\aPackage\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x01R\x04cost\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1f\n" +
	"\vtariff_code\x18\a \x01(\tR\n" +
	"tariffCode\"\a\n" +
	"\x05Empty2\x92\x03\n" +
	"\x0eAuctionService\x125\n" +
	"\bPlaceBid\x12\x13.auction.BidRequest\x1a\x14.auction.BidResponse\x12?\n" +
	"\x10GetBidsByPackage\x12\x14.auction.BidsRequest\x1a\x15.auction.BidsResponse\x12:\n" +
	"\x15GetAuctioningPackages\x12\x0e.auction.Empty\x1a\x11.auction.Packages\x126\n" +
	"\x11GetFailedPackages\x12\x0e.auction.Empty\x1a\x11.auction.Packages\x12.\n" +
	"\fStartAuction\x12\x0e.auction.Empty\x1a\x0e.auction.Empty\x120\n" +
	"\x0eRepeateAuction\x12\x0e.auction.Empty\x1a\x0e.auction.Empty\x122\n" +
	"\n" +
	"StreamBids\x12\x14.auction.BidsRequest\x1a\f.auction.Bid0\x01B=Z;github.com/maksroxx/DeliveryService/proto/auction;auctionpbb\x06proto3"

var (
	file_auction_auction_proto_rawDescOnce sync.Once
	file_auction_auction_proto_rawDescData []byte
)

func file_auction_auction_proto_rawDescGZIP() []byte {
	file_auction_auction_proto_rawDescOnce.Do(func() {
		file_auction_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auction_auction_proto_rawDesc), len(file_auction_auction_proto_rawDesc)))
	})
	return file_auction_auction_proto_rawDescData
}

var file_auction_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_auction_auction_proto_goTypes = []any{
	(*BidRequest)(nil),   // 0: auction.BidRequest
	(*BidResponse)(nil),  // 1: auction.BidResponse
	(*BidsRequest)(nil),  // 2: auction.BidsRequest
	(*BidsResponse)(nil), // 3: auction.BidsResponse
	(*Bid)(nil),          // 4: auction.Bid
	(*Packages)(nil),     // 5: auction.Packages
	(*Package)(nil),      // 6: auction.Package
	(*Empty)(nil),        // 7: auction.Empty
}
var file_auction_auction_proto_depIdxs = []int32{
	4, // 0: auction.BidsResponse.bids:type_name -> auction.Bid
	6, // 1: auction.Packages.package:type_name -> auction.Package
	0, // 2: auction.AuctionService.PlaceBid:input_type -> auction.BidRequest
	2, // 3: auction.AuctionService.GetBidsByPackage:input_type -> auction.BidsRequest
	7, // 4: auction.AuctionService.GetAuctioningPackages:input_type -> auction.Empty
	7, // 5: auction.AuctionService.GetFailedPackages:input_type -> auction.Empty
	7, // 6: auction.AuctionService.StartAuction:input_type -> auction.Empty
	7, // 7: auction.AuctionService.RepeateAuction:input_type -> auction.Empty
	2, // 8: auction.AuctionService.StreamBids:input_type -> auction.BidsRequest
	1, // 9: auction.AuctionService.PlaceBid:output_type -> auction.BidResponse
	3, // 10: auction.AuctionService.GetBidsByPackage:output_type -> auction.BidsResponse
	5, // 11: auction.AuctionService.GetAuctioningPackages:output_type -> auction.Packages
	5, // 12: auction.AuctionService.GetFailedPackages:output_type -> auction.Packages
	7, // 13: auction.AuctionService.StartAuction:output_type -> auction.Empty
	7, // 14: auction.AuctionService.RepeateAuction:output_type -> auction.Empty
	4, // 15: auction.AuctionService.StreamBids:output_type -> auction.Bid
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auction_auction_proto_init() }
func file_auction_auction_proto_init() {
	if File_auction_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auction_auction_proto_rawDesc), len(file_auction_auction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auction_auction_proto_goTypes,
		DependencyIndexes: file_auction_auction_proto_depIdxs,
		MessageInfos:      file_auction_auction_proto_msgTypes,
	}.Build()
	File_auction_auction_proto = out.File
	file_auction_auction_proto_goTypes = nil
	file_auction_auction_proto_depIdxs = nil
}
