server:
  address: ":8333"
  shutdown_timeout: 30s

database:
  type: "mongodb"
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "logistics"

kafka:
  brokers:
    - "localhost:9092"
  topics:
    - "package-events"
    - "pay-events"
  groupID: "package-consumers"
  version: "7.3.0"