server:
  address: ":8333"
  shutdown_timeout: 30s

database:
  type: "mongodb"
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "logistics"

kafka:
  brokers:
    - "localhost:9092"
  topics: 
    - "pay-events"
    - "payment-events"
    - "expired-packages"
  groupID: "package-consumers"
  version: "7.3.0"

calculator:
  grpc_address: "localhost:50051"