server:
  address: ":1234"

database:
  uri: "mongodb://localhost:27017"
  name: "logistics"

kafka:
  brokers:
    - "localhost:9092"
  topic: "package-events"
  version: "7.3.0"
calculator:
  url: "http://localhost:8121"