server:
  address: ":5678"

database:
  driver: "postgres"
  uri: "mongodb://localhost:27017"
  name: "logistics"


postgres:
  host: "localhost"
  port: 5432
  user: "myuser"
  password: "mypassword"
  dbname: "mydatabase"
  sslmode: "disable"

kafka:
  brokers:
    - "localhost:9092"
  consumerTopic: "payment-events"
  producerTopic: "pay-events"
  groupID: "payment-consumers"
  version: "7.3.0"