server:
  address: ":5678"
  grpc_address: ":50053"

database:
  driver: "mongo"
  uri: "mongodb://mongo:27017"
  name: "logistics"

postgres:
  host: "postgres-db"
  port: 5432
  user: "myuser"
  password: "mypassword"
  dbname: "mydatabase"
  sslmode: "disable"

kafka:
  brokers:
    - "kafka:29092"
  consumerTopic: "payment-events"
  producerTopic:
    - "pay-events"
    - "paid-packages"
  groupID: "payment-consumers"
  version: "7.3.0"